import { Providers } from "./Providers"
import "./globals.css"

export const metadata = {
  title: "IMDb",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen text-gray-700 select-none dark:bg-gray-700 dark:text-gray-200 transition-colors duration-300 ">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
